from turtle import *
window = Screen()
tulip = Turtle()

bgcolor("lightblue")

# Vẽ thân cây
tulip.penup()
tulip.goto(0, -200)
# tulip.pendown()
# tulip.color("green")
# tulip.pensize(10)
# tulip.setheading(90)
# tulip.forward(250)

# # Vẽ lá trái
# penup()
# goto(-20, -100)
# setheading(150)
# pendown()
# pensize(3)
# fillcolor("lightgreen")
# begin_fill()
# circle(50, 100)
# left(80)
# circle(50, 100)
# end_fill()

# # Vẽ lá phải
# penup()
# goto(20, -150)
# setheading(30)
# pendown()
# fillcolor("lightgreen")
# begin_fill()
# circle(50, 100)
# right(80)
# circle(50, 100)
# end_fill()

# # Vẽ cánh hoa 1 (trái)
# penup()
# goto(-50, 50)
# setheading(60)
# pendown()
# pensize(2)
# color("red")
# fillcolor("red")
# begin_fill()
# circle(70, 80)
# left(110)
# circle(70, 80)
# end_fill()

# # Vẽ cánh hoa 2 (giữa)
# penup()
# goto(0, 60)
# setheading(90)
# pendown()
# fillcolor("crimson")
# begin_fill()
# circle(80, 80)
# left(110)
# circle(80, 80)
# end_fill()

# # Vẽ cánh hoa 3 (phải)
# penup()
# goto(50, 50)
# setheading(120)
# pendown()
# fillcolor("red")
# begin_fill()
# circle(70, 80)
# left(110)
# circle(70, 80)
# end_fill()

# # Nhụy hoa
# penup()
# goto(0, 20)
# pendown()
# dot(20, "yellow")

# hideturtle()
# done()
window.mainloop()